#!/bin/sh
set -e

DEST="/app/share/mmxod"
mkdir -p "$DEST"

# Extract the contents of the downloaded Debian archive
bsdtar -xf debian_game.zip -C "$DEST"

# Extract Windows contents to a temporary directory to copy only the assets
mkdir -p /tmp/win_temp
bsdtar -xf win_game.zip -C /tmp/win_temp
cp -r /tmp/win_temp/assets "$DEST/"
rm -rf /tmp/win_temp
